package com.here.entity;

import java.util.Date;

public class ExamRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_room.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_room.paper_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer paperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_room.user_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_room.take_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer takeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_room.status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_room.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_room.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_room.id
     *
     * @return the value of exam_room.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_room.id
     *
     * @param id the value for exam_room.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_room.paper_id
     *
     * @return the value of exam_room.paper_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_room.paper_id
     *
     * @param paperId the value for exam_room.paper_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_room.user_id
     *
     * @return the value of exam_room.user_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_room.user_id
     *
     * @param userId the value for exam_room.user_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_room.take_time
     *
     * @return the value of exam_room.take_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getTakeTime() {
        return takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_room.take_time
     *
     * @param takeTime the value for exam_room.take_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setTakeTime(Integer takeTime) {
        this.takeTime = takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_room.status
     *
     * @return the value of exam_room.status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_room.status
     *
     * @param status the value for exam_room.status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_room.create_time
     *
     * @return the value of exam_room.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_room.create_time
     *
     * @param createTime the value for exam_room.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_room.update_time
     *
     * @return the value of exam_room.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_room.update_time
     *
     * @param updateTime the value for exam_room.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}