package com.here.entity;

import java.util.Date;

public class ExamInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_info.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_info.exam_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer examId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_info.question_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_info.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_info.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_info.id
     *
     * @return the value of exam_info.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_info.id
     *
     * @param id the value for exam_info.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_info.exam_id
     *
     * @return the value of exam_info.exam_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_info.exam_id
     *
     * @param examId the value for exam_info.exam_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_info.question_id
     *
     * @return the value of exam_info.question_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_info.question_id
     *
     * @param questionId the value for exam_info.question_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_info.create_time
     *
     * @return the value of exam_info.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_info.create_time
     *
     * @param createTime the value for exam_info.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_info.update_time
     *
     * @return the value of exam_info.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_info.update_time
     *
     * @param updateTime the value for exam_info.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}