package com.here.entity;

public class QuestionWithBLOBs extends Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.analysis
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private String analysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.analysis
     *
     * @return the value of question.analysis
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.analysis
     *
     * @param analysis the value for question.analysis
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer
     *
     * @return the value of question.answer
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer
     *
     * @param answer the value for question.answer
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}