package com.here.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.options
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Object options;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.cat_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.init_score
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private BigDecimal initScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.type
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.level
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Short level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.note
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date updateTime;

    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.options
     *
     * @return the value of question.options
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Object getOptions() {
        return options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.options
     *
     * @param options the value for question.options
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setOptions(Object options) {
        this.options = options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.cat_id
     *
     * @return the value of question.cat_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.cat_id
     *
     * @param catId the value for question.cat_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setCatId(Integer catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.init_score
     *
     * @return the value of question.init_score
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public BigDecimal getInitScore() {
        return initScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.init_score
     *
     * @param initScore the value for question.init_score
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setInitScore(BigDecimal initScore) {
        this.initScore = initScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.type
     *
     * @return the value of question.type
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.type
     *
     * @param type the value for question.type
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.level
     *
     * @return the value of question.level
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.level
     *
     * @param level the value for question.level
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setLevel(Short level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.note
     *
     * @return the value of question.note
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.note
     *
     * @param note the value for question.note
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.create_time
     *
     * @return the value of question.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.create_time
     *
     * @param createTime the value for question.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.update_time
     *
     * @return the value of question.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.update_time
     *
     * @param updateTime the value for question.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}