package com.here.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.room_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.user_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.award_status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Short awardStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.print_status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Short printStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.reate_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date reateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.room_id
     *
     * @return the value of score.room_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.room_id
     *
     * @param roomId the value for score.room_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.user_id
     *
     * @return the value of score.user_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.user_id
     *
     * @param userId the value for score.user_id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.status
     *
     * @return the value of score.status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.status
     *
     * @param status the value for score.status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.award_status
     *
     * @return the value of score.award_status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Short getAwardStatus() {
        return awardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.award_status
     *
     * @param awardStatus the value for score.award_status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setAwardStatus(Short awardStatus) {
        this.awardStatus = awardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.print_status
     *
     * @return the value of score.print_status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Short getPrintStatus() {
        return printStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.print_status
     *
     * @param printStatus the value for score.print_status
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setPrintStatus(Short printStatus) {
        this.printStatus = printStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.reate_time
     *
     * @return the value of score.reate_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getReateTime() {
        return reateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.reate_time
     *
     * @param reateTime the value for score.reate_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setReateTime(Date reateTime) {
        this.reateTime = reateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.update_time
     *
     * @return the value of score.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.update_time
     *
     * @param updateTime the value for score.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}