package com.here.entity;

import java.util.Date;

public class SysInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.mac
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private String mac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.sys_mark
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private String sysMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.create_user
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.create_ip
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    private String createIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.id
     *
     * @return the value of sys_info.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.id
     *
     * @param id the value for sys_info.id
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.mac
     *
     * @return the value of sys_info.mac
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.mac
     *
     * @param mac the value for sys_info.mac
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.sys_mark
     *
     * @return the value of sys_info.sys_mark
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public String getSysMark() {
        return sysMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.sys_mark
     *
     * @param sysMark the value for sys_info.sys_mark
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setSysMark(String sysMark) {
        this.sysMark = sysMark == null ? null : sysMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.create_time
     *
     * @return the value of sys_info.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.create_time
     *
     * @param createTime the value for sys_info.create_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.update_time
     *
     * @return the value of sys_info.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.update_time
     *
     * @param updateTime the value for sys_info.update_time
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.create_user
     *
     * @return the value of sys_info.create_user
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.create_user
     *
     * @param createUser the value for sys_info.create_user
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.create_ip
     *
     * @return the value of sys_info.create_ip
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public String getCreateIp() {
        return createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.create_ip
     *
     * @param createIp the value for sys_info.create_ip
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    public void setCreateIp(String createIp) {
        this.createIp = createIp == null ? null : createIp.trim();
    }
}