package com.here.dao;

import com.here.entity.ExamInfo;
import com.here.entity.ExamInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    long countByExample(ExamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int deleteByExample(ExamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int insert(ExamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int insertSelective(ExamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    List<ExamInfo> selectByExample(ExamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    ExamInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") ExamInfo record, @Param("example") ExamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int updateByExample(@Param("record") ExamInfo record, @Param("example") ExamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int updateByPrimaryKeySelective(ExamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int updateByPrimaryKey(ExamInfo record);
}