package com.here.dao;

import com.here.entity.SysInfo;
import com.here.entity.SysInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    long countByExample(SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int deleteByExample(SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int insert(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int insertSelective(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    List<SysInfo> selectByExample(SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    SysInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysInfo record, @Param("example") SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int updateByExample(@Param("record") SysInfo record, @Param("example") SysInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int updateByPrimaryKeySelective(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbg.generated Mon Oct 15 11:20:36 CST 2018
     */
    int updateByPrimaryKey(SysInfo record);
}